name = "send-canva-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
BASE_URL = "https://send-canva-worker.brickstack.workers.dev"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "send-canva-files"

[[d1_databases]]
binding = "DB"
database_name = "send-canva-db"
database_id = "26ec631f-f1ad-4799-a646-1ddee5682eb5"
