name = "send-canva-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[vars]
BASE_URL = "https://send-canva-worker.asksend.workers.dev"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "send-canva-files"

[[d1_databases]]
binding = "DB"
database_name = "send-canva-db"
database_id = "0829962d-bb24-457a-9549-3f9e00d4bceb"
